Update README.md
CDCgov/data-exchange-hl7 pull request #861
Opened 2023-04-21 18:16 UTC by mscaldas2012

2023-04-21 20:00 UTC, dancing-goats requested changes

2023-04-21 20:00 UTC, dancing-goats commented on fns-hl7-pipeline/fn-mmg-validator/README.md
> +* **MMWR Year** -Validate specifically MMWR Year (this violates our pattern of fully configurable rules, this one is hardcoded but was requested by customer to be included)
missing space after `-` and before `Validate`

2023-05-22 19:11 UTC, marcia-schulman approved these changes

2023-05-22 19:13 UTC, marcia-schulman approved these changes

2023-05-22 19:14 UTC, merged